services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mySQL
  mySQL:
    image: mysql:8.0.39
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: cs3
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3304:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: